{% set name = "mpb" %}
{% set version = "1.8.0" %}
{% set sha256 = "2d2fa2a7b656057e8902665aa3f05e82a603f36bb5db17bc914663d3da59f9c9" %}

package:
  name: {{ name }}
  version: {{version}}

source:
  fn: {{ name }}-{{version}}.tar.gz
  url: https://github.com/stevengj/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ pin_compatible('openblas', max_pin='x.x.x') }}
    - {{ pin_compatible('hdf5', max_pin='x.x.x') }}
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libblas
    - libcblas
    - fftw
    - hdf5
    - libctl >=4.2.0
  run:
    - fftw
    - libctl >=4.2.0

test:
  commands:
    - test -f ${PREFIX}/lib/libmpb${SHLIB_EXT}

about:
  home: http:/github.com/stevengj/mpb
  license: GPL-2.0
  license_file: COPYING
  summary: MIT Photonic-Bands - computation of photonic band structures in periodic media
  doc_url: http://mpb.readthedocs.io
  dev_url: https://github.com/stevengj/mpb

extra:
  recipe-maintainers:
    - ChristopherHogan
