travis:
  secure:
    BINSTAR_TOKEN: fgQP1aaMzc/1eTWQDNm+8VPs2dEFVv+r3HAA0MOjHTAijr2uSbUlkBheMWouEFG5x4n1aYfQ0qYa6UvMsqUDebxwI9JSbdCcJxCHVagz3eAde9wACK2cWYwEghE3fkt8/uSvciNLgYBaFihSFy1p7AFoJR9J1MqKt6RiEX3V4XtL8nh4hN0g1P+CgVBVj8/yfM/1HMhHF+3/N7QSooJzSTlbk8H2Y8sszFn4gd9FvSuIapjeBwva2HVvO6pMVNVLwD3hYdQsTIqnYWMzYc5gC9t9RIKYUw/IP4rfns/8i916NeOBVu7Ykvtu4YHSPrWMl8I5AAnkKeyoWV2AuqCvG2B+GIkn00FDj7se9cojqlSnL4Pv0OZ/rLeQio18nnJsWTGy+2kBwX6GvYLflXiSPOYHhBLoPS3P+u9cnpOo7fxcS7RVTOVn0rvBZO07Bn/nsIkm5FOAyCAkmvDVx0tQg5WRIqWpko4wDhWPH+k8sd/YTCEObGgL3kFRlaU1wl88+QwyBtHc27OslD/FcLJ0Ggo6MQ53lr/iX0shT+KIWvcqUk0/iROLZjuDSEsUKyrmO6zNpp6B0L+egmi9meiKT6I5hTzKClS1vfbpzUW5vQKzfO4U+FTCl+6MAcQm83Ro14teQ4R6rAYILzMfPhBCJnTDpgVGv3eDs/e6DQtHx14=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
